
title: Nic Atlas
email: nicholasaatlas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My Personal Website
url: "https://nicatlas.me" # the base hostname & protocol for your site, e.g. http://example.com
icon: favicon.ico
twitter_username: twitter
github_username:  NicAtlas

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
