# Setup
title:               'Nic Atlas'
tagline:             'Website'
description:         'This website serves as a hub for some of my fun, tech-related projects and endeavors. Check out my GitHub!  <a href="https://github.com/NicAtlas" target="_blank">@NicAtlas</a> :)'
url:                 https://nicatlas.me
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nic Atlas
  url:               https://twitter.com/
  email:             nicholasaatlas@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
